name: CMake Multi-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TESTS: true
  CONAN_PRESET: conan-release

permissions:
  actions: read
  deployments: write
  contents: write
  id-token: write
  security-events: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            conan_settings: -s os=Windows -s arch=x86_64 -s compiler=msvc -s compiler.version=194 -s compiler.cppstd=23 -s compiler.runtime=dynamic

          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            conan_settings: -s os=Linux -s arch=x86_64 -s compiler=gcc -s compiler.version=11 -s compiler.libcxx=libstdc++11 -s compiler.cppstd=23

          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            conan_settings: -s os=Macos -s arch=x86_64 -s compiler=apple-clang -s compiler.version=14 -s compiler.libcxx=libc++ -s compiler.cppstd=23

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Create Conan Short Path
        if: matrix.os == 'windows-latest'
        run: |
          New-Item -ItemType Directory -Force -Path "C:\C2"
          echo "CONAN_USER_HOME=C:\C2" >> $env:GITHUB_ENV
          echo "CONAN_USER_HOME_SHORT=C:\C2" >> $env:GITHUB_ENV

      - name: Install Build Tools
        uses: lukka/get-cmake@latest

      - name: Install Conan
        if: matrix.os != 'macos-latest'
        uses: turtlebrowser/get-conan@main

      - name: Install Conan on macOS
        if: matrix.os == 'macos-latest'
        run: brew install conan

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Setup GCC
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 110

      - name: Detect Conan Profile
        run: conan profile detect --force

      - name: Install Conan Dependencies
        shell: bash
        run: |
          conan install . --build=missing ${{ matrix.conan_settings }} -s build_type=${{ matrix.build_type }} -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

      - name: Configure CMake
        run: cmake --preset ${{ env.CONAN_PRESET }}

      - name: Build Project
        run: cmake --build --preset ${{ env.CONAN_PRESET }}

      - name: Run Tests
        if: env.BUILD_TESTS == 'true'
        run: ctest --preset ${{ env.CONAN_PRESET }}