name: CMake Multi-Platform Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TESTS: true
  CONAN_PRESET: conan-release

permissions:
  actions: read
  deployments: write
  contents: write
  id-token: write
  security-events: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            conan_profile: ../../Profiles/windows-latest.conanprofile
            extra_settings: -s compiler.runtime=dynamic

          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            conan_profile: ../../Profiles/ubuntu-latest.conanprofile
            extra_settings: -s compiler.libcxx=libstdc++11

          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
            conan_profile: ../../Profiles/macos-latest.conanprofile
            extra_settings: -s compiler.libcxx=libc++

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set CONAN_USER_HOME for Windows
        if: matrix.os == 'windows-latest'
        run: |
          echo "CONAN_USER_HOME=C:\C2" >> $env:GITHUB_ENV

      - name: Install Build Tools
        uses: lukka/get-cmake@latest

      - name: Install Conan
        uses: turtlebrowser/get-conan@main

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Setup GCC
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 110
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 110

      - name: Install Conan Dependencies
        shell: bash
        run: |
          conan install . --build=missing --profile=${{ matrix.conan_profile }} ${{ matrix.extra_settings }} -s build_type=${{ matrix.build_type }} -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

      - name: Configure CMake
        run: cmake --preset ${{ env.CONAN_PRESET }}

      - name: Build Project
        run: cmake --build --preset ${{ env.CONAN_PRESET }}

      - name: Run Tests
        if: env.BUILD_TESTS == 'true'
        run: ctest --preset ${{ env.CONAN_PRESET }}